// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: CAN_screen1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void LHindic_Animation(lv_obj_t * TargetObject, int delay);
void RHindic_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_MTS1200s
void ui_MTS1200s_screen_init(void);
lv_obj_t * ui_MTS1200s;
lv_obj_t * ui_GEARlabel1;
lv_obj_t * ui_rpmlabel;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
void ui_event_GearNumber(lv_event_t * e);
lv_obj_t * ui_GearNumber;
void ui_event_RPMbar(lv_event_t * e);
lv_obj_t * ui_RPMbar;
void ui_event_Speednumber(lv_event_t * e);
lv_obj_t * ui_Speednumber;
void ui_event_rpmNumber(lv_event_t * e);
lv_obj_t * ui_rpmNumber;
void ui_event_fuellevelbar(lv_event_t * e);
lv_obj_t * ui_fuellevelbar;
void ui_event_fuelevelnumber(lv_event_t * e);
lv_obj_t * ui_fuelevelnumber;
void ui_event_engtempnumber(lv_event_t * e);
lv_obj_t * ui_engtempnumber;
void ui_event_Airtempnumber(lv_event_t * e);
lv_obj_t * ui_Airtempnumber;
void ui_event_Timenumberhr(lv_event_t * e);
lv_obj_t * ui_Timenumberhr;
void ui_event_Timenumbermins(lv_event_t * e);
lv_obj_t * ui_Timenumbermins;
void ui_event_keysense(lv_event_t * e);
lv_obj_t * ui_keysense;
void ui_event_MapbarH(lv_event_t * e);
lv_obj_t * ui_MapbarH;
void ui_event_MapVbar(lv_event_t * e);
lv_obj_t * ui_MapVbar;
lv_obj_t * ui_mapVlabel;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
void ui_event_mapVnum(lv_event_t * e);
lv_obj_t * ui_mapVnum;
void ui_event_mapHnum(lv_event_t * e);
lv_obj_t * ui_mapHnum;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label16;
void ui_event_oxyVnum(lv_event_t * e);
lv_obj_t * ui_oxyVnum;
void ui_event_xyHnum(lv_event_t * e);
lv_obj_t * ui_xyHnum;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
void ui_event_APSbar(lv_event_t * e);
lv_obj_t * ui_APSbar;
void ui_event_TPSbar(lv_event_t * e);
lv_obj_t * ui_TPSbar;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
void ui_event_Batnum(lv_event_t * e);
lv_obj_t * ui_Batnum;
void ui_event_MBeamLabel(lv_event_t * e);
lv_obj_t * ui_MBeamLabel;
void ui_event_Odometer(lv_event_t * e);
lv_obj_t * ui_Odometer;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1009271004[1] = {&ui_img_90875330};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void LHindic_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 50);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void RHindic_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 50);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_GearNumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        GearNumber(e);
    }
}

void ui_event_RPMbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rpmbar(e);
    }
}

void ui_event_Speednumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SpeedNumber(e);
    }
}

void ui_event_rpmNumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rpmnumber(e);
    }
}

void ui_event_fuellevelbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        fuelevelbar(e);
    }
}

void ui_event_fuelevelnumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        fuelevelnumber(e);
    }
}

void ui_event_engtempnumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        engtempnumber(e);
    }
}

void ui_event_Airtempnumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Airtempnumber(e);
    }
}

void ui_event_Timenumberhr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Timenumberhr(e);
    }
}

void ui_event_Timenumbermins(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Timenumbermins(e);
    }
}

void ui_event_keysense(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        keysense(e);
    }
}

void ui_event_MapbarH(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mapbarH(e);
    }
}

void ui_event_MapVbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mapbarV(e);
    }
}

void ui_event_mapVnum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mapVnum(e);
    }
}

void ui_event_mapHnum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mapHnum(e);
    }
}

void ui_event_oxyVnum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OxyVnum(e);
    }
}

void ui_event_xyHnum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OxyHnum(e);
    }
}

void ui_event_APSbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        APSbar(e);
    }
}

void ui_event_TPSbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TPSbar(e);
    }
}

void ui_event_Batnum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Batnum(e);
    }
}

void ui_event_MBeamLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_opacity_set(ui_MBeamLabel, 255);
    }
}

void ui_event_Odometer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Kilometers(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MTS1200s_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MTS1200s);
}
