// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: CAN_screen1

#ifndef _CAN_SCREEN1_UI_H
#define _CAN_SCREEN1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void LHindic_Animation(lv_obj_t * TargetObject, int delay);
void RHindic_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_MTS1200s
void ui_MTS1200s_screen_init(void);
extern lv_obj_t * ui_MTS1200s;
extern lv_obj_t * ui_GEARlabel1;
extern lv_obj_t * ui_rpmlabel;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_GearNumber(lv_event_t * e);
extern lv_obj_t * ui_GearNumber;
void ui_event_RPMbar(lv_event_t * e);
extern lv_obj_t * ui_RPMbar;
void ui_event_Speednumber(lv_event_t * e);
extern lv_obj_t * ui_Speednumber;
void ui_event_rpmNumber(lv_event_t * e);
extern lv_obj_t * ui_rpmNumber;
void ui_event_fuellevelbar(lv_event_t * e);
extern lv_obj_t * ui_fuellevelbar;
void ui_event_fuelevelnumber(lv_event_t * e);
extern lv_obj_t * ui_fuelevelnumber;
void ui_event_engtempnumber(lv_event_t * e);
extern lv_obj_t * ui_engtempnumber;
void ui_event_Airtempnumber(lv_event_t * e);
extern lv_obj_t * ui_Airtempnumber;
void ui_event_Timenumberhr(lv_event_t * e);
extern lv_obj_t * ui_Timenumberhr;
void ui_event_Timenumbermins(lv_event_t * e);
extern lv_obj_t * ui_Timenumbermins;
void ui_event_keysense(lv_event_t * e);
extern lv_obj_t * ui_keysense;
void ui_event_MapbarH(lv_event_t * e);
extern lv_obj_t * ui_MapbarH;
void ui_event_MapVbar(lv_event_t * e);
extern lv_obj_t * ui_MapVbar;
extern lv_obj_t * ui_mapVlabel;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
void ui_event_mapVnum(lv_event_t * e);
extern lv_obj_t * ui_mapVnum;
void ui_event_mapHnum(lv_event_t * e);
extern lv_obj_t * ui_mapHnum;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label16;
void ui_event_oxyVnum(lv_event_t * e);
extern lv_obj_t * ui_oxyVnum;
void ui_event_xyHnum(lv_event_t * e);
extern lv_obj_t * ui_xyHnum;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
void ui_event_APSbar(lv_event_t * e);
extern lv_obj_t * ui_APSbar;
void ui_event_TPSbar(lv_event_t * e);
extern lv_obj_t * ui_TPSbar;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
void ui_event_Batnum(lv_event_t * e);
extern lv_obj_t * ui_Batnum;
void ui_event_MBeamLabel(lv_event_t * e);
extern lv_obj_t * ui_MBeamLabel;
void ui_event_Odometer(lv_event_t * e);
extern lv_obj_t * ui_Odometer;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1477404486);    // assets/ducati-multistrada-1200-s-pikes-peak-special-edition.png
LV_IMG_DECLARE(ui_img_90875330);    // assets/key-icon-26616.png

// FONTS
LV_FONT_DECLARE(ui_font_Ariallarge);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
