// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: CAN_screen1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void GearNumber(lv_event_t * e);
void rpmbar(lv_event_t * e);
void SpeedNumber(lv_event_t * e);
void rpmnumber(lv_event_t * e);
void fuelevelbar(lv_event_t * e);
void fuelevelnumber(lv_event_t * e);
void engtempnumber(lv_event_t * e);
void Airtempnumber(lv_event_t * e);
void Timenumberhr(lv_event_t * e);
void Timenumbermins(lv_event_t * e);
void keysense(lv_event_t * e);
void mapbarH(lv_event_t * e);
void mapbarV(lv_event_t * e);
void mapVnum(lv_event_t * e);
void mapHnum(lv_event_t * e);
void OxyVnum(lv_event_t * e);
void OxyHnum(lv_event_t * e);
void APSbar(lv_event_t * e);
void TPSbar(lv_event_t * e);
void Batnum(lv_event_t * e);
void Kilometers(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
