// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: CAN_screen1

#include "ui.h"

void GearNumber(lv_event_t * e)
{
	// Your code here
}

void rpmbar(lv_event_t * e)
{
	// Your code here
}

void SpeedNumber(lv_event_t * e)
{
	// Your code here
}

void rpmnumber(lv_event_t * e)
{
	// Your code here
}

void fuelevelbar(lv_event_t * e)
{
	// Your code here
}

void fuelevelnumber(lv_event_t * e)
{
	// Your code here
}

void engtempnumber(lv_event_t * e)
{
	// Your code here
}

void Airtempnumber(lv_event_t * e)
{
	// Your code here
}

void Timenumberhr(lv_event_t * e)
{
	// Your code here
}

void Timenumbermins(lv_event_t * e)
{
	// Your code here
}

void keysense(lv_event_t * e)
{
	// Your code here
}

void mapbarH(lv_event_t * e)
{
	// Your code here
}

void mapbarV(lv_event_t * e)
{
	// Your code here
}

void mapVnum(lv_event_t * e)
{
	// Your code here
}

void mapHnum(lv_event_t * e)
{
	// Your code here
}

void OxyVnum(lv_event_t * e)
{
	// Your code here
}

void OxyHnum(lv_event_t * e)
{
	// Your code here
}

void APSbar(lv_event_t * e)
{
	// Your code here
}

void TPSbar(lv_event_t * e)
{
	// Your code here
}

void Batnum(lv_event_t * e)
{
	// Your code here
}

void Kilometers(lv_event_t * e)
{
	// Your code here
}
