// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: CAN_screen1

#include "ui.h"

void ui_MTS1200s_screen_init(void)
{
    ui_MTS1200s = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MTS1200s, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_radius(ui_MTS1200s, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MTS1200s, &ui_img_1477404486, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_MTS1200s, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MTS1200s, lv_color_hex(0xFAF4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MTS1200s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_opa(ui_MTS1200s, 100, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_GEARlabel1 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_GEARlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEARlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEARlabel1, 48);
    lv_obj_set_y(ui_GEARlabel1, 152);
    lv_obj_set_align(ui_GEARlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GEARlabel1, "Gear");
    lv_obj_set_style_text_color(ui_GEARlabel1, lv_color_hex(0x81D939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEARlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEARlabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmlabel = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_rpmlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmlabel, -279);
    lv_obj_set_y(ui_rpmlabel, 112);
    lv_obj_set_align(ui_rpmlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmlabel, "RPM");
    lv_obj_set_style_text_font(ui_rpmlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -5);
    lv_obj_set_y(ui_Label12, -211);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Speed");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xE2F116), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -347);
    lv_obj_set_y(ui_Label15, -90);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "FUEL litres");

    ui_Label10 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -351);
    lv_obj_set_y(ui_Label10, -211);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Eng Temp");

    ui_Label11 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -315);
    lv_obj_set_y(ui_Label11, -154);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "c");

    ui_Label1 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -351);
    lv_obj_set_y(ui_Label1, 133);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Air Temp");

    ui_Label3 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -316);
    lv_obj_set_y(ui_Label3, 171);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "c");

    ui_Label13 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -214);
    lv_obj_set_y(ui_Label13, -116);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Time");

    ui_Label14 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -213);
    lv_obj_set_y(ui_Label14, -78);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, ":");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -237);
    lv_obj_set_y(ui_Label2, 74);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "0");

    ui_Label4 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 212);
    lv_obj_set_y(ui_Label4, 72);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "10,000");

    ui_Label5 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -7);
    lv_obj_set_y(ui_Label5, 75);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "5,000");

    ui_GearNumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_GearNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GearNumber, 50);
    lv_obj_set_y(ui_GearNumber, 191);
    lv_obj_set_align(ui_GearNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GearNumber, "N");
    lv_obj_set_style_text_color(ui_GearNumber, lv_color_hex(0xD3D3D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GearNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_GearNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearNumber, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GearNumber, lv_color_hex(0xF6F6F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GearNumber, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GearNumber, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GearNumber, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GearNumber, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GearNumber, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GearNumber, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMbar = lv_bar_create(ui_MTS1200s);
    lv_bar_set_mode(ui_RPMbar, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_RPMbar, 1, 12000);
    lv_bar_set_value(ui_RPMbar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RPMbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMbar, 548);
    lv_obj_set_height(ui_RPMbar, 48);
    lv_obj_set_x(ui_RPMbar, 32);
    lv_obj_set_y(ui_RPMbar, 113);
    lv_obj_set_align(ui_RPMbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RPMbar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RPMbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_RPMbar, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_RPMbar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_RPMbar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMbar, lv_color_hex(0x0F9921), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RPMbar, lv_color_hex(0xED0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RPMbar, 3000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RPMbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RPMbar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_RPMbar, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_RPMbar, lv_color_hex(0x0A0A0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_RPMbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RPMbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RPMbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RPMbar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RPMbar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_RPMbar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_RPMbar, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_RPMbar, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_RPMbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_RPMbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMbar, lv_color_hex(0x02050B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RPMbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RPMbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_RPMbar, lv_color_hex(0x010104), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RPMbar, lv_color_hex(0x080101), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RPMbar, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RPMbar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_RPMbar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_RPMbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_RPMbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_RPMbar, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_RPMbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Speednumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Speednumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speednumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speednumber, 1);
    lv_obj_set_y(ui_Speednumber, -151);
    lv_obj_set_align(ui_Speednumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speednumber, "0");
    lv_obj_set_style_text_color(ui_Speednumber, lv_color_hex(0xE9E717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speednumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speednumber, &ui_font_Ariallarge, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Speednumber, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Speednumber, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Speednumber, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Speednumber, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmNumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_rpmNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmNumber, -203);
    lv_obj_set_y(ui_rpmNumber, 114);
    lv_obj_set_align(ui_rpmNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmNumber, "0");
    lv_obj_set_style_text_color(ui_rpmNumber, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rpmNumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rpmNumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rpmNumber, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rpmNumber, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuellevelbar = lv_bar_create(ui_MTS1200s);
    lv_bar_set_mode(ui_fuellevelbar, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_fuellevelbar, 0, 20);
    lv_obj_set_width(ui_fuellevelbar, 26);
    lv_obj_set_height(ui_fuellevelbar, 128);
    lv_obj_set_x(ui_fuellevelbar, -350);
    lv_obj_set_y(ui_fuellevelbar, -7);
    lv_obj_set_align(ui_fuellevelbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fuellevelbar, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_fuellevelbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_set_style_radius(ui_fuellevelbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuellevelbar, lv_color_hex(0x0A0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuellevelbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fuellevelbar, lv_color_hex(0x757171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fuellevelbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fuellevelbar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_fuellevelbar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuellevelbar, lv_color_hex(0xF30606), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_fuellevelbar, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_fuellevelbar, lv_color_hex(0x216014),
                                   LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_fuellevelbar, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_fuellevelbar, 155, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_fuellevelbar, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_transform_pivot_x(ui_fuellevelbar, 90, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_transform_pivot_y(ui_fuellevelbar, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);

    lv_obj_set_style_radius(ui_fuellevelbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuellevelbar, lv_color_hex(0x28E065), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuellevelbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_fuellevelbar, lv_color_hex(0x237F31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_fuellevelbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_fuellevelbar, 155, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_fuellevelbar, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_fuellevelbar, lv_color_hex(0x989090), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_fuellevelbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_fuellevelbar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_fuellevelbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_fuelevelnumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_fuelevelnumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelevelnumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelevelnumber, -351);
    lv_obj_set_y(ui_fuelevelnumber, -59);
    lv_obj_set_align(ui_fuelevelnumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuelevelnumber, "0");
    lv_obj_set_style_text_color(ui_fuelevelnumber, lv_color_hex(0xFBFBF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelevelnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_engtempnumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_engtempnumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_engtempnumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_engtempnumber, -354);
    lv_obj_set_y(ui_engtempnumber, -161);
    lv_obj_set_align(ui_engtempnumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_engtempnumber, "0");
    lv_obj_set_style_text_color(ui_engtempnumber, lv_color_hex(0xF7F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_engtempnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_engtempnumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_engtempnumber, lv_color_hex(0xF9F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_engtempnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_engtempnumber, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_engtempnumber, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_engtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_engtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_engtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Airtempnumber = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Airtempnumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Airtempnumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Airtempnumber, -346);
    lv_obj_set_y(ui_Airtempnumber, 173);
    lv_obj_set_align(ui_Airtempnumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Airtempnumber, "0");
    lv_obj_set_style_text_font(ui_Airtempnumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Airtempnumber, lv_color_hex(0xF9F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Airtempnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Airtempnumber, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Airtempnumber, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Airtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Airtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Airtempnumber, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timenumberhr = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Timenumberhr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timenumberhr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Timenumberhr, -237);
    lv_obj_set_y(ui_Timenumberhr, -77);
    lv_obj_set_align(ui_Timenumberhr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timenumberhr, "13");
    lv_obj_set_style_text_font(ui_Timenumberhr, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Timenumberhr, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Timenumberhr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Timenumberhr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Timenumberhr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Timenumberhr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Timenumberhr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Timenumberhr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timenumbermins = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Timenumbermins, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timenumbermins, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Timenumbermins, -188);
    lv_obj_set_y(ui_Timenumbermins, -76);
    lv_obj_set_align(ui_Timenumbermins, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timenumbermins, "14");
    lv_obj_set_style_text_font(ui_Timenumbermins, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Timenumbermins, lv_color_hex(0xFEF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Timenumbermins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Timenumbermins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Timenumbermins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Timenumbermins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Timenumbermins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Timenumbermins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keysense = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_keysense, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_keysense, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_keysense, 347);
    lv_obj_set_y(ui_keysense, 189);
    lv_obj_set_align(ui_keysense, LV_ALIGN_CENTER);
    lv_label_set_text(ui_keysense, "No Key");
    lv_obj_set_style_text_font(ui_keysense, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_keysense, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_keysense, &ui_img_90875330, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_keysense, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_keysense, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_keysense, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_keysense, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_keysense, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapbarH = lv_bar_create(ui_MTS1200s);
    lv_bar_set_range(ui_MapbarH, 0, 1020);
    lv_bar_set_value(ui_MapbarH, 1003, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MapbarH, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MapbarH, 150);
    lv_obj_set_height(ui_MapbarH, 10);
    lv_obj_set_x(ui_MapbarH, -96);
    lv_obj_set_y(ui_MapbarH, 213);
    lv_obj_set_align(ui_MapbarH, LV_ALIGN_CENTER);

    ui_MapVbar = lv_bar_create(ui_MTS1200s);
    lv_bar_set_range(ui_MapVbar, 0, 1020);
    lv_bar_set_value(ui_MapVbar, 1003, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MapVbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MapVbar, 150);
    lv_obj_set_height(ui_MapVbar, 10);
    lv_obj_set_x(ui_MapVbar, -99);
    lv_obj_set_y(ui_MapVbar, 172);
    lv_obj_set_align(ui_MapVbar, LV_ALIGN_CENTER);

    ui_mapVlabel = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_mapVlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapVlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapVlabel, -222);
    lv_obj_set_y(ui_mapVlabel, 172);
    lv_obj_set_align(ui_mapVlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mapVlabel, "MAP V");

    ui_Label6 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -222);
    lv_obj_set_y(ui_Label6, 206);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Map H");

    ui_Label7 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -29);
    lv_obj_set_y(ui_Label7, 193);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "1020");

    ui_Label8 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -175);
    lv_obj_set_y(ui_Label8, 191);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "0");

    ui_mapVnum = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_mapVnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapVnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapVnum, -266);
    lv_obj_set_y(ui_mapVnum, 172);
    lv_obj_set_align(ui_mapVnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mapVnum, "1010");

    ui_mapHnum = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_mapHnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapHnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapHnum, -266);
    lv_obj_set_y(ui_mapHnum, 206);
    lv_obj_set_align(ui_mapHnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mapHnum, "1010");

    ui_Label9 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 274);
    lv_obj_set_y(ui_Label9, 175);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "OXY V");

    ui_Label16 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 275);
    lv_obj_set_y(ui_Label16, 206);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "OXY H");

    ui_oxyVnum = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_oxyVnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oxyVnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oxyVnum, 205);
    lv_obj_set_y(ui_oxyVnum, 175);
    lv_obj_set_align(ui_oxyVnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oxyVnum, "0");

    ui_xyHnum = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_xyHnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xyHnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xyHnum, 206);
    lv_obj_set_y(ui_xyHnum, 204);
    lv_obj_set_align(ui_xyHnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xyHnum, "0");

    ui_Label17 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 341);
    lv_obj_set_y(ui_Label17, 8);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "TPS");

    ui_Label18 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 340);
    lv_obj_set_y(ui_Label18, -33);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "APS");

    ui_APSbar = lv_bar_create(ui_MTS1200s);
    lv_bar_set_mode(ui_APSbar, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_value(ui_APSbar, 4, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_APSbar, 4, LV_ANIM_OFF);
    lv_obj_set_width(ui_APSbar, 313);
    lv_obj_set_height(ui_APSbar, 10);
    lv_obj_set_x(ui_APSbar, 152);
    lv_obj_set_y(ui_APSbar, -31);
    lv_obj_set_align(ui_APSbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_APSbar, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_APSbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_APSbar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_TPSbar = lv_bar_create(ui_MTS1200s);
    lv_bar_set_mode(ui_TPSbar, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_value(ui_TPSbar, 4, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TPSbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TPSbar, 320);
    lv_obj_set_height(ui_TPSbar, 10);
    lv_obj_set_x(ui_TPSbar, 155);
    lv_obj_set_y(ui_TPSbar, 8);
    lv_obj_set_align(ui_TPSbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TPSbar, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_TPSbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_TPSbar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_Label19 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -2);
    lv_obj_set_y(ui_Label19, -12);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "0");

    ui_Label20 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 306);
    lv_obj_set_y(ui_Label20, -13);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "100");

    ui_Label21 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 314);
    lv_obj_set_y(ui_Label21, -199);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Battery");

    ui_Label22 = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 371);
    lv_obj_set_y(ui_Label22, -170);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Volts\nx10");

    ui_Batnum = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Batnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Batnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Batnum, 314);
    lv_obj_set_y(ui_Batnum, -168);
    lv_obj_set_align(ui_Batnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Batnum, "0");
    lv_obj_set_style_text_font(ui_Batnum, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Batnum, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Batnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Batnum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Batnum, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Batnum, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Batnum, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Batnum, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Batnum, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBeamLabel = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_MBeamLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MBeamLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MBeamLabel, 274);
    lv_obj_set_y(ui_MBeamLabel, -97);
    lv_obj_set_align(ui_MBeamLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MBeamLabel, "BEAM");
    lv_label_set_recolor(ui_MBeamLabel, "true");
    lv_obj_add_state(ui_MBeamLabel, LV_STATE_USER_1);       /// States
    lv_obj_clear_flag(ui_MBeamLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MBeamLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_MBeamLabel, lv_color_hex(0x430FF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MBeamLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MBeamLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MBeamLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_MBeamLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MBeamLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MBeamLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MBeamLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MBeamLabel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MBeamLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Odometer = lv_label_create(ui_MTS1200s);
    lv_obj_set_width(ui_Odometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Odometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Odometer, -210);
    lv_obj_set_y(ui_Odometer, 30);
    lv_obj_set_align(ui_Odometer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Odometer, "000000");
    lv_obj_set_style_text_color(ui_Odometer, lv_color_hex(0xFAF2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Odometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Odometer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Odometer, lv_color_hex(0xF0E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Odometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Odometer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Odometer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Odometer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Odometer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Odometer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GearNumber, ui_event_GearNumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RPMbar, ui_event_RPMbar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Speednumber, ui_event_Speednumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rpmNumber, ui_event_rpmNumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fuellevelbar, ui_event_fuellevelbar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fuelevelnumber, ui_event_fuelevelnumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_engtempnumber, ui_event_engtempnumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Airtempnumber, ui_event_Airtempnumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Timenumberhr, ui_event_Timenumberhr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Timenumbermins, ui_event_Timenumbermins, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_keysense, ui_event_keysense, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MapbarH, ui_event_MapbarH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MapVbar, ui_event_MapVbar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mapVnum, ui_event_mapVnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mapHnum, ui_event_mapHnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oxyVnum, ui_event_oxyVnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xyHnum, ui_event_xyHnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_APSbar, ui_event_APSbar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TPSbar, ui_event_TPSbar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Batnum, ui_event_Batnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MBeamLabel, ui_event_MBeamLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Odometer, ui_event_Odometer, LV_EVENT_ALL, NULL);

}
